import { Character } from './types';
import 'react-native-get-random-values';
import { v4 as uuid } from 'uuid';

export function createDefaultCharacter(): Character {
  const id = uuid();
  return {
    id,
    name: 'Новый персонаж',
    playerName: '',
    ancestry: '',
    heritage: '',
    background: '',
    characterClass: '',
    level: 1,
    xp: 0,
    languages: ['Общий'],
    abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
    hp: { max: 10, current: 10, temp: 0 },
    dying: 0,
    wounded: 0,
    heroPoints: 1,
    armorClass: { proficiency: 'U', itemBonus: 0, miscBonus: 0, maxDexBonus: null },
    saves: {
      fortitude: 'T', fortitudeBonus: 0,
      reflex: 'T', reflexBonus: 0,
      will: 'T', willBonus: 0,
    },
    perception: { proficiency: 'T', miscBonus: 0 },
    speed: 25,
    conditions: [],
    skills: {
      acrobatics:   { proficiency: 'U', miscBonus: 0, armorPenalty: true  },
      athletics:    { proficiency: 'U', miscBonus: 0, armorPenalty: true  },
      crafting:     { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      deception:    { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      diplomacy:    { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      intimidation: { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      lore1:        { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      lore2:        { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      medicine:     { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      nature:       { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      occultism:    { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      performance:  { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      religion:     { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      society:      { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      stealth:      { proficiency: 'U', miscBonus: 0, armorPenalty: true  },
      survival:     { proficiency: 'U', miscBonus: 0, armorPenalty: false },
      thievery:     { proficiency: 'U', miscBonus: 0, armorPenalty: true  },
    },
    lore1Name: 'Знание',
    lore2Name: 'Знание',
    feats: [],
    strikes: [],
    weaponProficiencies: { unarmed: 'T', simple: 'U', martial: 'U', advanced: 'U' },
    armorProficiencies: { unarmored: 'T', light: 'U', medium: 'U', heavy: 'U' },
    armorCheckPenalty: 0,
    inventory: [],
    wealth: { pp: 0, gp: 0, sp: 0, cp: 0 },
    magic: {
      tradition: 'arcane',
      type: 'prepared',
      attackProficiency: 'U',
      attackMiscBonus: 0,
      dcMiscBonus: 0,
      slots: {
        1: { max: 0, remaining: 0 },
        2: { max: 0, remaining: 0 },
        3: { max: 0, remaining: 0 },
        4: { max: 0, remaining: 0 },
        5: { max: 0, remaining: 0 },
        6: { max: 0, remaining: 0 },
        7: { max: 0, remaining: 0 },
        8: { max: 0, remaining: 0 },
        9: { max: 0, remaining: 0 },
        10: { max: 0, remaining: 0 },
      },
      spells: [],
      focusPoints: 0,
      focusMax: 0,
      focusSpells: [],
      innateSpells: [],
      rituals: [],
    },
    classDCProficiency: 'T',
    classDCMiscBonus: 0,
  };
}
